module Physics
	# Character height is 168 cm (about 5'6")
	#~ CHARACTER_HEIGHT_PX = 110.0
	#~ CHARACTER_HEIGHT_PX = 310.0
	CHARACTER_HEIGHT_PX = 446.0
	
	CHARACTER_HEIGHT_CM = 168.0
	#~ CHARACTER_HEIGHT_CM = 128.0
	SCALE = CHARACTER_HEIGHT_PX/CHARACTER_HEIGHT_CM*100 # Pixels per meter
end
